# Site settings
title: Superhaufen|Minifien
email: superhaufen@superhaufen.com
description: Heike Pfisterer's portfolio page
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site

# Build settings  -----------------
markdown: kramdown
# JEKYLL_ENV=production jekyll build
# eg  # {% if jekyll.environment == "production" %}
      #   {% include disqus.html %}
      # {% endif %}

highlighter: pygments

# Header and Sidebar section -----------------
header-logo: /img/logos/Superhaufen_Logo.png
header-logo-minifien: /img/logos/Minifien_Logo.png
sidebar-logo: /img/logos/Minifien_small.png

links:
    - name: home
      url: /
    - name: superhaufen
      url: /superhaufen
    - name: minifien
      url: /minifien
    - name: about
      url: /about
    - name: contact
      url: /contact
    - name: impressum
      url: /impressum

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Styles in projekt / blog pages  -----------------
heading-style: "{: .project-txt .project-heading}"
text-style-superhaufen: "{: .project-txt}"
text-style-minifien: "{: .project-txt-minfien}"
heading-style: "{: .project-heading }"
heading-style-contact: "{: .contact-heading }"
image-style: "{: .project-img .u-max-full-width}"
text-style-contact-margin: "{: .contact-txt-margin }"
text-style-contact-no-margin: "{: .contact-txt-no-margin }"